import { DataTable } from "@/components/ui/data-table";
import { columnsTableSchedulesDemo } from "./columnsTableSchedulesDemo";

export function PageSchedulesDemo() {
  const listData = [
    {
      schedule_id: 1,
      order_id: 1,
      order_date: "12/31/2022",
      est_start_time: "09:00:00",
      est_end_time: "12:00:00",
      start_point: 1,
      end_point: 2,
      load_name: "stone",
      load_amount: 1,
      load_weight: 10,
    },
    {
      schedule_id: 2,
      order_id: 2,
      order_date: "12/31/2022",
      est_start_time: "13:00:00",
      est_end_time: "16:00:00",
      start_point: 3,
      end_point: 4,
      load_name: "stone",
      load_amount: 2,
      load_weight: 20,
    },
    {
      schedule_id: 3,
      order_id: 3,
      order_date: "12/31/2022",
      est_start_time: "17:00:00",
      est_end_time: "20:00:00",
      start_point: 5,
      end_point: 6,
      load_name: "iron",
      load_amount: 3,
      load_weight: 30,
    },
    {
      schedule_id: 4,
      order_id: 4,
      order_date: "12/31/2022",
      est_start_time: "17:00:00",
      est_end_time: "20:00:00",
      start_point: 7,
      end_point: 8,
      load_name: "stone",
      load_amount: 4,
      load_weight: 30,
    },
    {
      schedule_id: 5,
      order_id: 5,
      order_date: "01/01/2023",
      est_start_time: "08:00:00",
      est_end_time: "11:00:00",
      start_point: 9,
      end_point: 10,
      load_name: "stone",
      load_amount: 5,
      load_weight: 15,
    },
    {
      schedule_id: 6,
      order_id: 6,
      order_date: "01/01/2023",
      est_start_time: "12:00:00",
      est_end_time: "15:00:00",
      start_point: 11,
      end_point: 12,
      load_name: "iron",
      load_amount: 6,
      load_weight: 25,
    },
    {
      schedule_id: 7,
      order_id: 7,
      order_date: "01/01/2023",
      est_start_time: "16:00:00",
      est_end_time: "19:00:00",
      start_point: 13,
      end_point: 14,
      load_name: "stone",
      load_amount: 7,
      load_weight: 35,
    },
    {
      schedule_id: 8,
      order_id: 8,
      order_date: "01/02/2023",
      est_start_time: "09:00:00",
      est_end_time: "12:00:00",
      start_point: 15,
      end_point: 1,
      load_name: "stone",
      load_amount: 8,
      load_weight: 40,
    },
    {
      schedule_id: 9,
      order_id: 9,
      order_date: "01/02/2023",
      est_start_time: "13:00:00",
      est_end_time: "16:00:00",
      start_point: 2,
      end_point: 3,
      load_name: "iron",
      load_amount: 9,
      load_weight: 45,
    },
    {
      schedule_id: 10,
      order_id: 10,
      order_date: "01/02/2023",
      est_start_time: "17:00:00",
      est_end_time: "20:00:00",
      start_point: 4,
      end_point: 5,
      load_name: "stone",
      load_amount: 10,
      load_weight: 50,
    },
    {
      schedule_id: 11,
      order_id: 11,
      order_date: "01/03/2023",
      est_start_time: "08:00:00",
      est_end_time: "11:00:00",
      start_point: 6,
      end_point: 7,
      load_name: "stone",
      load_amount: 11,
      load_weight: 55,
    },
    {
      schedule_id: 12,
      order_id: 12,
      order_date: "01/03/2023",
      est_start_time: "12:00:00",
      est_end_time: "15:00:00",
      start_point: 8,
      end_point: 9,
      load_name: "iron",
      load_amount: 12,
      load_weight: 60,
    },
    {
      schedule_id: 13,
      order_id: 13,
      order_date: "01/03/2023",
      est_start_time: "16:00:00",
      est_end_time: "19:00:00",
      start_point: 10,
      end_point: 11,
      load_name: "stone",
      load_amount: 13,
      load_weight: 65,
    },
    {
      schedule_id: 14,
      order_id: 14,
      order_date: "01/04/2023",
      est_start_time: "09:00:00",
      est_end_time: "12:00:00",
      start_point: 12,
      end_point: 13,
      load_name: "stone",
      load_amount: 14,
      load_weight: 70,
    },
    {
      schedule_id: 15,
      order_id: 15,
      order_date: "01/04/2023",
      est_start_time: "13:00:00",
      est_end_time: "16:00:00",
      start_point: 14,
      end_point: 15,
      load_name: "iron",
      load_amount: 15,
      load_weight: 75,
    },
  ];

  return (
    <>
      <div className="space-y-5">
        <h2 className="text-3xl font-bold">Schedule Demo</h2>
        <DataTable
          data={listData}
          columns={columnsTableSchedulesDemo}
          filterSearchByColumn="order_date"
        />
      </div>
    </>
  );
}
