services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/code
      - /code/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSocket port
    volumes:
      - ./mosquitto:/mosquitto/config
    restart: unless-stopped

  agv_server:
    build: ./agv_server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./agv_server:/code/src
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - MQTT_BROKER_HOST=mqtt
    depends_on:
      - db
      - mqtt
