services:
  server:
    build: ./agv_server
    container_name: django_app
    ports:
      - 8000:8000
    volumes:
      - ./agv_server:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  client:
    build: ./frontend
    container_name: react_app
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_started

volumes:
  postgres_db:
