services:
  server:
    build: ./agv_server
    container_name: django_app
    ports:
      - 8000:8000
    volumes:
      - ./agv_server:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    # volumes:
    #   - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  client:
    build: ./frontend
    container_name: react_app
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_started

volumes:
  postgres_db:
  # redis_data:
