services:
  server:
    build: ./agv_server
    container_name: django_app
    ports:
      - 8000:8000
    volumes:
      - ./agv_server:/app
    depends_on:
      - db
      - redis
      - mosquitto
    env_file:
      - .env.prod
    environment:
      - MQTT_BROKER=mosquitto # Use the service name in Docker

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  client:
    build: ./frontend
    container_name: react_app
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_started

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT port
      - "9001:9001" # WebSocket port
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    restart: always

volumes:
  postgres_db:
  mosquitto_data:
