# Generated by Django 5.1.7 on 2025-04-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule_generate', '0011_alter_schedule_initial_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agv',
            fields=[
                ('agv_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('current_node', models.IntegerField(help_text='Current position (v_c^i)')),
                ('next_node', models.IntegerField(help_text='Next point to visit (v_n^i)', null=True)),
                ('reserved_node', models.IntegerField(help_text='Reserved point (v_r^i)', null=True)),
                ('motion_state', models.IntegerField(choices=[(0, 'Idle'), (1, 'Moving'), (2, 'Waiting')], default=0, help_text='AGV state (SA^i)')),
                ('spare_flag', models.BooleanField(default=False, help_text='Indicates if AGV has spare points (F^i)')),
                ('in_sequential_shared_points', models.BooleanField(default=False, help_text='Indicates if AGV is currently in sequential shared points')),
                ('is_deadlocked', models.BooleanField(default=False, help_text='Indicates if AGV is currently in a deadlock situation')),
                ('last_spare_point', models.IntegerField(blank=True, help_text='Last spare point used to resolve deadlock', null=True)),
                ('active_schedule', models.OneToOneField(blank=True, help_text='Current active schedule being executed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_agv', to='schedule_generate.schedule')),
            ],
            options={
                'verbose_name': 'AGV',
                'verbose_name_plural': 'AGVs',
            },
        ),
    ]
