# Generated by Django 5.1.7 on 2025-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agv',
            name='previous_node',
            field=models.IntegerField(help_text='Last point visited', null=True),
        ),
    ]
