# Generated by Django 5.1.7 on 2025-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agv',
            name='preferred_parking_node',
            field=models.IntegerField(default=1, help_text='Preferred parking point (v_p^i)'),
        ),
    ]
