# Generated by Django 5.1.7 on 2025-04-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0002_agv_preferred_parking_node'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agv',
            options={'ordering': ['agv_id'], 'verbose_name': 'AGV', 'verbose_name_plural': 'AGVs'},
        ),
    ]
