# Generated by Django 5.1.7 on 2025-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agv_data", "0002_agv_previous_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="agv",
            name="direction_change",
            field=models.IntegerField(
                choices=[
                    (0, "Go straight"),
                    (1, "Turn reverse"),
                    (2, "Turn left"),
                    (3, "Turn right"),
                ],
                help_text="Direction the AGV should turn to after reaching a node",
                null=True,
            ),
        ),
    ]
