# Generated by Django 5.1.7 on 2025-04-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0003_agv_direction_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agv',
            name='direction_change',
            field=models.IntegerField(choices=[(0, 'Go straight'), (1, 'Turn around'), (2, 'Turn left'), (3, 'Turn right')], help_text='Direction the AGV should turn to after reaching a node', null=True),
        ),
    ]
