# Generated by Django 5.1.7 on 2025-04-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0003_alter_agv_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agv',
            name='current_node',
            field=models.IntegerField(help_text='Current position (v_c^i)', null=True),
        ),
    ]
