# Generated by Django 5.1.7 on 2025-04-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0004_alter_agv_current_node'),
        ('schedule_generate', '0014_remove_schedule_sp_remove_schedule_spare_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agv',
            name='in_sequential_shared_points',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='is_deadlocked',
        ),
        migrations.RemoveField(
            model_name='agv',
            name='last_spare_point',
        ),
        migrations.AddField(
            model_name='agv',
            name='spare_points',
            field=models.JSONField(default=dict, help_text='SP^i: mapping of shared points to their allocated spare points'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='active_schedule',
            field=models.OneToOneField(blank=True, help_text='Currently executing schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_agv', to='schedule_generate.schedule'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='current_node',
            field=models.IntegerField(help_text='Current position (v_c^i): point where AGV is located or last left', null=True),
        ),
        migrations.AlterField(
            model_name='agv',
            name='motion_state',
            field=models.IntegerField(choices=[(0, 'Idle'), (1, 'Moving'), (2, 'Waiting')], default=0, help_text='AGV state (SA^i) as defined in Definition 7'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='preferred_parking_node',
            field=models.IntegerField(help_text='Preferred parking point for AGV'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='spare_flag',
            field=models.BooleanField(default=False, help_text='F^i: indicates if AGV moves along shared points with sufficient spare points'),
        ),
    ]
