# Generated by Django 5.1.7 on 2025-06-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0005_alter_agv_direction_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agv',
            old_name='residual_path',
            new_name='remaining_path',
        ),
    ]
