# Generated by Django 5.1.7 on 2025-04-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0005_remove_agv_in_sequential_shared_points_and_more'),
        ('order_data', '0003_rename_end_point_order_parking_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agv',
            name='active_schedule',
        ),
        migrations.AddField(
            model_name='agv',
            name='active_order',
            field=models.OneToOneField(blank=True, help_text='Currently executing order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_agv', to='order_data.order'),
        ),
        migrations.AddField(
            model_name='agv',
            name='cp',
            field=models.JSONField(default=list, help_text='CP: Shared points with other AGVs'),
        ),
        migrations.AddField(
            model_name='agv',
            name='initial_path',
            field=models.JSONField(default=list, help_text='P_i^j: Path of AGV i performing task j. Once generated, will not change.'),
        ),
        migrations.AddField(
            model_name='agv',
            name='residual_path',
            field=models.JSONField(default=list, help_text='Pi_i: Remaining points to be visited by AGV i.'),
        ),
        migrations.AddField(
            model_name='agv',
            name='scp',
            field=models.JSONField(default=list, help_text='SCP: Sequential shared points'),
        ),
    ]
