# Generated by Django 5.1.7 on 2025-06-01 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agv_data", "0007_rename_cp_agv_common_nodes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agv",
            old_name="scp",
            new_name="adjacent_common_nodes",
        ),
    ]
