# Generated by Django 5.1.7 on 2025-06-15 09:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0012_convert_jsonfield_to_arrayfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agv',
            name='adjacent_common_nodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='ACN (Adjacent common nodes). Name in research paper: SCP (Sequential shared points)', size=None),
        ),
        migrations.AlterField(
            model_name='agv',
            name='common_nodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='CN (Common nodes). Name in research paper: CP (Shared points with other AGVs)', size=None),
        ),
        migrations.AlterField(
            model_name='agv',
            name='remaining_path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='Pi_i: Remaining points to be visited by AGV i. Name in research paper: residual path', size=None),
        ),
    ]
