# Generated by Django 5.1.7 on 2025-06-16 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agv_data", "0014_headondeadlockpair"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeadOnDeadlockPair",
        ),
    ]
