# Generated by Django 5.1.7 on 2025-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_data', '0015_delete_headondeadlockpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='agv',
            name='deadlock_partner_agv_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the AGV that this AGV had head-on deadlock with (used to trigger control policy when partner moves)', null=True),
        ),
        migrations.AddField(
            model_name='agv',
            name='waiting_for_deadlock_resolution',
            field=models.BooleanField(default=False, help_text='Indicates if AGV is waiting due to being moved to backup node during deadlock resolution'),
        ),
    ]
