# Generated by Django 5.1.7 on 2025-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField()),
                ('order_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('est_end_time', models.TimeField(default='00:00:00')),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
                ('load_name', models.CharField(max_length=100)),
                ('load_amount', models.IntegerField(default=0)),
                ('load_weight', models.IntegerField(default=0)),
                ('instruction_set', models.TextField(default='[]')),
            ],
        ),
    ]
