# Generated by Django 5.1.7 on 2025-03-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['schedule_id']},
        ),
    ]
