# Generated by Django 5.1.7 on 2025-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generate', '0002_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='sequential_shared_points',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shared_points',
            field=models.TextField(default='[]'),
        ),
    ]
