# Generated by Django 5.1.7 on 2025-04-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generate', '0003_schedule_sequential_shared_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='sequential_shared_points',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shared_points',
        ),
    ]
