# Generated by Django 5.1.7 on 2025-04-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generate', '0006_schedule_cp_schedule_scp_schedule_sp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
