# Generated by Django 5.1.7 on 2025-04-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generate', '0007_alter_schedule_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='instruction_set',
            new_name='initial_path',
        ),
    ]
