# Generated by Django 5.1.7 on 2025-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generate', '0009_schedule_residual_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='initial_path',
            field=models.JSONField(default='[]'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='residual_path',
            field=models.JSONField(default='[]'),
        ),
    ]
