# Generated by Django 5.1.7 on 2025-04-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generate', '0010_alter_schedule_initial_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='initial_path',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='residual_path',
            field=models.JSONField(default=list),
        ),
    ]
