# Generated by Django 5.1.7 on 2025-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_generate', '0012_schedule_assigned_agv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='state',
            field=models.IntegerField(default=2),
        ),
    ]
