# Generated by Django 5.1.7 on 2025-03-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
                ('load_name', models.CharField(max_length=100)),
                ('load_amount', models.IntegerField(default=0)),
                ('load_weight', models.IntegerField(default=0)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='name')),
            ],
        ),
    ]
