# Generated by Django 5.1.7 on 2025-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('parking_node', models.IntegerField()),
                ('storage_node', models.IntegerField()),
                ('workstation_node', models.IntegerField()),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
