# Generated by Django 5.1.7 on 2025-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_data', '0002_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='end_point',
            new_name='parking_node',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_point',
            new_name='storage_node',
        ),
        migrations.RemoveField(
            model_name='order',
            name='load_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='load_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='load_weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
        migrations.AddField(
            model_name='order',
            name='workstation_node',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
