# Generated by Django 5.1.7 on 2025-04-24 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_count', models.IntegerField(default=0, help_text='Total number of nodes in the map', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Map Data',
                'verbose_name_plural': 'Map Data',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node1', models.IntegerField(help_text='Starting node of the connection', validators=[django.core.validators.MinValueValidator(1)])),
                ('node2', models.IntegerField(help_text='Ending node of the connection', validators=[django.core.validators.MinValueValidator(1)])),
                ('distance', models.FloatField(help_text='Distance between the nodes', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
                'indexes': [models.Index(fields=['node1'], name='map_data_co_node1_4dc7a3_idx'), models.Index(fields=['node2'], name='map_data_co_node2_749ff4_idx')],
                'unique_together': {('node1', 'node2')},
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node1', models.IntegerField(help_text='Reference node (starting point)', validators=[django.core.validators.MinValueValidator(1)])),
                ('node2', models.IntegerField(help_text='Target node (ending point)', validators=[django.core.validators.MinValueValidator(1)])),
                ('direction', models.IntegerField(choices=[(1, 'North'), (2, 'East'), (3, 'South'), (4, 'West')], help_text='Cardinal direction from node1 to node2 (1=North, 2=East, 3=South, 4=West)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'indexes': [models.Index(fields=['node1'], name='map_data_di_node1_bf8d80_idx'), models.Index(fields=['node2'], name='map_data_di_node2_3b3986_idx')],
                'unique_together': {('node1', 'node2')},
            },
        ),
    ]
