# Generated by Django 5.1.7 on 2025-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0003_mapdata_delete_edge_delete_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node1', models.IntegerField()),
                ('node2', models.IntegerField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node1', models.IntegerField()),
                ('node2', models.IntegerField()),
                ('direction', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mapdata',
            name='connection_matrix',
        ),
        migrations.RemoveField(
            model_name='mapdata',
            name='direction_matrix',
        ),
        migrations.AddField(
            model_name='mapdata',
            name='node_count',
            field=models.IntegerField(default=0),
        ),
    ]
