# Generated by Django 5.1.7 on 2025-04-12 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0004_connection_direction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='mapdata',
            options={'verbose_name': 'Map Data', 'verbose_name_plural': 'Map Data'},
        ),
        migrations.AlterField(
            model_name='connection',
            name='distance',
            field=models.FloatField(help_text='Distance between the nodes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='connection',
            name='node1',
            field=models.IntegerField(help_text='Starting node of the connection', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='connection',
            name='node2',
            field=models.IntegerField(help_text='Ending node of the connection', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.IntegerField(choices=[(1, 'North'), (2, 'East'), (3, 'South'), (4, 'West')], help_text='Cardinal direction from node1 to node2 (1=North, 2=East, 3=South, 4=West)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='direction',
            name='node1',
            field=models.IntegerField(help_text='Reference node (starting point)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='direction',
            name='node2',
            field=models.IntegerField(help_text='Target node (ending point)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='node_count',
            field=models.IntegerField(default=0, help_text='Total number of nodes in the map', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('node1', 'node2')},
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together={('node1', 'node2')},
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['node1'], name='map_data_co_node1_4dc7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['node2'], name='map_data_co_node2_749ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='direction',
            index=models.Index(fields=['node1'], name='map_data_di_node1_bf8d80_idx'),
        ),
        migrations.AddIndex(
            model_name='direction',
            index=models.Index(fields=['node2'], name='map_data_di_node2_3b3986_idx'),
        ),
    ]
